package util;

import java.util.HashMap;

/**
 *
 * @author Juan Pablo
 */
public class Mensajes {

    public static HashMap<String, String> mensaje = new HashMap<String, String>() {
        {
            put("tit","SAAN");
            put("err", "Error");
            put("reg", "Registrado");
            put("usuInc", "Usuario o contraseña incorrecto");
            put("eli", "Eliminado");
            put("recu", "Recuperación de contraseña");
            put("codrecu", "Código de recuperación: ");
            put("mod", "Modificado");
            put("ideMate", "Identificacion de la materia");
            put("gru", "Grupo");
            put("Nonotas", "Materia sin notas");
            put("Nogrup", "Materia sin grupos");
            put("megru", "Mejores grupos");
            put("estper", "Estudiantes que van perdiendo");
            put("ini", "Inicio");
            put("saan", "SISTEMA ACADÉMICO ASISTENTE DE NOTAS");
            put("esp", "Español");
            put("ing", "Ingles");
            put("inisec", "Iniciar sesión");
            put("menu", "Menú");
            put("Ganosinno", "El estudiante no va perdiendo o no tiene notas");
            put("Noestnot", "Estudiante sin notas");
            put("registro", "Registro");
            put("modifico", "modifico");
            put("matrM", "Matricula modificada");
            put("borro", "borro");
            put("cuerpo_borro", "se le borro la nota con identificación ");
            put("cuerpo_borro2", " de la materia ");
            put("cuerpo_resto", "Su nota con ");
            put("cuerpo_resto2", " con identificación de ");
            put("cuerpo_resto3", " fue de ");
            put("cuerpo_resto4", " y vale ");
            put("cuerpo_resto5", " % de la nota final");
            put("asunto", "se le ");
            put("asunto2", " una nota");
            // mensajes de juan diego - estudiantes perdiendo
            put("nombre", "Nombre");
            put("Materia", "Materia");
            put("Numero", "Numero");
            put("Docente", "Docente");
            put("EstuPerd", "Estudiantes que van perdiendo");
            put("generar", "Generar datos ficticios");
            put("SAAN" , "SAAN");
            put("WEB" , "WEB");
            put("menuUser", "Menu de usuario");
            // mensajes de juan diego - recuperar contraseña
            put("recup" ,"¿Desea recuperar contraseña?");
            put("volver", "Volver a inicio");
            put("iniciar", "Inicie sesion en SAAN");
            put("placeholderCorreo", "Ingrese su documento o email");
            put("placeholderContra", "Escriba una contraseña");
            put("init", "Iniciar");
            put("olvido", "Olvido contraseña Saan");
            put("olvido2", "¿Olvido su contraseña?");
            put("olvidoCuerpo", "Lo entendemos, solo ingrese su correo o documento para recuperarla.\n" +
"                    Recibira un codigo en breves momentos en su correo electronico.");
            put("yaCuenta", "¿Ya tienes una cuenta? ¡ingresa aqui!");
            put("placeholderOlvido", "Ingrese su correo");
            put("generarCodigo", "Generar codigo");
            put("juanD", "Juan Diego Marin Rodriguez");
            put("juanU", "Juan Felipe Usuga Villegas");
            put("juanP", "Juan Pablo Moya Alarcon");
            put("julian", "Julian Ospina Murgueitio");
            put("funcionalidades", "Funcionalidades especiales");
            put("enviarAct", "Enviar correos al actualizar, borrar, modificar y añadir una nota");
            put("generarRep", "Generar reportes de excel");
            put("mejoresGrupos", "Mostrar los mejores grupos");
            put("malosEstudiantes", "Mostrar los estudiantes que van perdiendo");
            put("recuperarcontra", "Recuperar contraseña");
            put("mejoresNotas", "Reporte de mejores notas");
            put("encontrarCor", "Encontrar correos de estudiantes y mandar eventos");
            put("cuando","Cuando..." );
            put("profNota", "Tu profesor sube las notas y no te avisa");
            put("contreaNew", "Escriba una nueva contraseña");
            put("contraConfirm", "Escriba de nuevo la contraseña");
            put("dataRec", "Recupere su contraseña, inserte una nueva.");
            put("codigoO", "Ingrese el codigo que le llego al correo");
            put("infoEnv", "Cambiar contraseña");
            put("eliNota", "Eliminación de nota");
            put("noSePuede", "No se puede eliminar al profesor, ya que tiene grupos en los que enseña");
            put("corInv", "Correo invalido");
            put("docReg", "El documento ya esta registrado");
            put("corReg", "El correo ya esta registrado");
            put("adminMod", "Administrador modificado");
            put("estuMod", "Estudiante modificado");
            put("maYaReg", "La materia ya tiene ese numero registrado");
            put("proNoReg", "El profesor no esta registrado");
            put("gruMod", "Grupo modificado");
            put("idReg", "El id ya esta registrado");
            put("matMod", "Materia modificada");
            put("proMod","Profesor modificado");
            put("matNoReg","La materia no esta registrada");
            put("infoUsu","Información usuario");
            put("adm","Administrador");
            put("nom:","Nombre:");
            put("doc:","Documento:");
            put("cor:","Correo:");
            put("con:","Contraseña:");
            put("noEnc","No encontrado");
            put("ideOCor","Identificación o correo");
            put("ingDocOCor","Ingrese el documento de identidad o correo electronico");
            put("busc","Buscar");
            put("busq","Busqueda");
            put("modi","Modificar");
            put("elim","Eliminar");
            put("rolAd", "Administrador");
            put("matTri", "Materias matriculadas");
            put("Codigo", "Codigo");
            put("Grupo", "Grupo");
            put("Ninguna", "Ninguna");
            put("Estudiante", "Estudiante");
            put("Idmat", "Id materia:");
            put("nomMat", "Nombre materia:");
            put("idProf", "Identificacion Profesor:");
            put("nomProf", "Nombre Profesor:");
            put("ideti", "Identificacion");
            put("notaFi", "Nota Final");
            put("Id:", "Id:");
            put("Creditos:" ,"Creditos:");
            put("Grupos", "Grupos");
            put("docProf", "Documento profesor");
            put("cantEst", "Cantidad estudiantes");
            put("matEn", "Materias en las que enseña");
            put("Admins", "Administradores");
            put("correo", "Correo");
            put("contras" , "Contraseña");
            put("edic", "Edicion");
            put("ingreName", "Ingrese el documento de identidad");
            put("ingrete", "Ingrese el nombre");
            put("ingreCor", "Ingrese el correo electronico");
            put("ingreCon", "Ingrese la contraseña");
            put("ingreNum", "Ingrese el numero del grupo");
            put("ingreDoc", "Ingrese el documento del profesor");
            put("Materias", "Materias");
            put("Id", "Id");
            put("Creditos", "Creditos");
            put("ingreId", "Ingrese el id");
            put("ingreCre", "Ingrese la cantidad de creditos");
            put("Profesores", "Profesores");
            put("Administradores", "Administradores");
            put("Registrar", "Registrar");
            put("Estudiantes", "Estudiantes");
            put("Grupos", "Grupos");
            put("ingreGrup", "Ingrese el Id del grupo");
            put("Profesor", "Profesor");
            // mensajes de Usuga
            put("nomprof", "Nombre:");
            put("docprof", "Documento:");
            put("corrprof", "Correo:");
            put("rolprof", "Rol:");
            put("prof", "Profesor");
            put("saan", "SAAN");
            put("numprof", "Número:");
            put("prof", "Profesor");
            put("idprof", "Id:");
            put("matprof", "Materia: ");
            put("creprof", "Creditos: ");
            put("notfound", "No encontrado");
            put("busprof", "Busqueda");
            put("iddprof", "Id");
            put("plidprof", "Ingrese el id");
            put("idmatprof", "Id Materia");
            put("plidmatprof", "Ingrese el id de la materia");
            put("busrpro", "Buscar");
            put("mattprof", "Materia");
            put("notprof", "Nota");
            put("valprof", "Valor:");
            put("porcenprof", "Porcentaje");
            put("modprof", "Modificar");
            put("delprof", "Eliminar");
            put("idgrupprof", "Id Grupo");
            put("idestuprof", "Id Estudiante");
            put("plhidestuprof", "Ingrese el id del estudiante");
            put("plhidgrup", "Ingrese el id del grupo");
            put("plhnameprof", "Ingrese el nombre deseado");
            put("passprof", "Contraseña");
            put("edprof", "Edición");
            put("nombbprof", "Nombre");
            put("dateprof", "Fecha");
            put("detailprof", "Detalles");
            put("regevnprof", "Registrar evento");
            put("plhnamevtprof", "Ingrese el nombre del evento");
            put("pldateprof", "Ingrese la fecha de un evento");
            put("plhdetprof", "Describa los detalles del evento");
            put("creaevnprof", "Creación Evento");
            put("notnotprof", "No hay notas que mostrar");
            put("plhvalprof", "Ingrese el valor");
            put("plhporprof", "Ingrese el porcentaje");
            put("regprof", "Registro");
            put("notsprof", "Notas");
            put("vallprof", "Valor");
            put("regnotprof", "Registrar");
            put("SAAN","SAAN");
            put("Web","Web");
            put("Nom","Nombre");
            put("Doc","Documento");
            put("Corr","Correo");
            put("Rol","Rol");
            put("Not","Nota");
            put("Id","Id");
            put("por","Porcentaje");
            put("val","Valor");
            put("mat","Materia");
            put("indoc","Ingrese su documento");
            put("idmat","Id materia");
            put("inmat","Ingrese el id de la materia");
            put("numgru","Numero grupo");
            put("ingru","Ingrese el numero del grupo");
            put("idnot","Id nota");
            put("innot","Ingrese el id de la nota");
            put("bus","Buscar");
            put("num","Numero");
            put("prof","Profesor");
            put("Noenc","No encontrado");
            put("busq","Busqueda");
            put("cre","Creditos");
            put("cantest","Cantidad de estudiantes");
            put("nin","Ninguno");
            put("est","Estudiante");
            put("cont","Contraseña");
            put("modr","Modificar");
            put("nucon","Ingrese nueva contraseña");
            put("ed","Edicion");
            put("nunom","Ingrese nuevo nombre");
            put("matr","Matricula");
            put("notF","Nota final");
            put("sem","Semestre");
            put("elir","Eliminar");
            put("regi","Registro");
            put("insem","Ingrese el semestre");
            put("regir","Registrar");
            put("op","Opciones");
            put("camcon","Cambiar contraseña");
            put("camnom","Cambiar nombre");
            put("conexit","Su contraseña ha sido cambiada exitosamente");
            put("nomexit","Su nombre ha sido cambiado exitosamente");
        }
    };

}
